In [4]:
import pandas as pd
df = pd.read_csv("data/raw/dataset_raw.csv")

In [5]:
df.head()

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,0,0,0,0,0
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,0,0,0,0,0
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,0,0,0,0,0
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,0,0,0,0,0
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,0,0,0,0,0

In [6]:
df.tail()

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
9995,9996,M24855,M,298.8,308.4,1604,29.5,14,0,0,0,0,0,0
9996,9997,H39410,H,298.9,308.4,1632,31.8,17,0,0,0,0,0,0
9997,9998,M24857,M,299.0,308.6,1645,33.4,22,0,0,0,0,0,0
9998,9999,H39412,H,299.0,308.7,1408,48.5,25,0,0,0,0,0,0
9999,10000,M24859,M,299.0,308.7,1500,40.2,30,0,0,0,0,0,0

In [8]:
df.sample(5)

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
5106,5107,L52286,L,304.0,313.3,1519,36.7,117,0,0,0,0,0,0
8300,8301,L55480,L,298.7,310.1,1558,37.6,44,0,0,0,0,0,0
8293,8294,M23153,M,298.9,310.4,1533,44.4,24,0,0,0,0,0,0
4347,4348,H33761,H,301.9,309.8,1724,27.5,126,0,0,0,0,0,0
7349,7350,L54529,L,299.7,310.2,1633,36.5,24,0,0,0,0,0,0

In [10]:
df.shape

(10000, 14)

In [11]:
df.size

140000

In [13]:
df.ndim

2

In [15]:
df.describe

<bound method NDFrame.describe of         UDI Product ID Type  Air temperature [K]  Process temperature [K]  \
0         1     M14860    M                298.1                    308.6
1         2     L47181    L                298.2                    308.7
2         3     L47182    L                298.1                    308.5
3         4     L47183    L                298.2                    308.6
4         5     L47184    L                298.2                    308.7
...     ...        ...  ...                  ...                      ...
9995   9996     M24855    M                298.8                    308.4
9996   9997     H39410    H                298.9                    308.4
9997   9998     M24857    M                299.0                    308.6
9998   9999     H39412    H                299.0                    308.7
9999  10000     M24859    M                299.0                    308.7

      Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Machine failure  \
0                       1551         42.8                0                0
1                       1408         46.3                3                0
2                       1498         49.4                5                0
3                       1433         39.5                7                0
4                       1408         40.0                9                0
...                      ...          ...              ...              ...
9995                    1604         29.5               14                0
9996                    1632         31.8               17                0
9997                    1645         33.4               22                0
9998                    1408         48.5               25                0
9999                    1500         40.2               30                0

      TWF  HDF  PWF  OSF  RNF
0       0    0    0    0    0
1       0    0    0    0    0
2       0    0    0    0    0
3       0    0    0    0    0
4       0    0    0    0    0
...   ...  ...  ...  ...  ...
9995    0    0    0    0    0
9996    0    0    0    0    0
9997    0    0    0    0    0
9998    0    0    0    0    0
9999    0    0    0    0    0

[10000 rows x 14 columns]>

In [16]:
df.isnull().sum()

UDI                        0
Product ID                 0
Type                       0
Air temperature [K]        0
Process temperature [K]    0
Rotational speed [rpm]     0
Torque [Nm]                0
Tool wear [min]            0
Machine failure            0
TWF                        0
HDF                        0
PWF                        0
OSF                        0
RNF                        0
dtype: int64

In [24]:
print(df["Machine failure"].value_counts())
print(df["TWF"].value_counts())
print(df["HDF"].value_counts())
print(df["PWF"].value_counts())
print(df["OSF"].value_counts())
print(df["RNF"].value_counts())

Machine failure
0    9661
1     339
Name: count, dtype: int64
TWF
0    9954
1      46
Name: count, dtype: int64
HDF
0    9885
1     115
Name: count, dtype: int64
PWF
0    9905
1      95
Name: count, dtype: int64
OSF
0    9902
1      98
Name: count, dtype: int64
RNF
0    9981
1      19
Name: count, dtype: int64

In [25]:
df.duplicated().sum()

np.int64(0)

In [26]:
df.columns

Index(['UDI', 'Product ID', 'Type', 'Air temperature [K]',
       'Process temperature [K]', 'Rotational speed [rpm]', 'Torque [Nm]',
       'Tool wear [min]', 'Machine failure', 'TWF', 'HDF', 'PWF', 'OSF',
       'RNF'],
      dtype='object')